[package]
name = "nexus-tester"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nexus-rt = { git = "https://github.com/nexus-xyz/nexus-zkvm.git", version = "0.1.0" }
